@startuml
hide footbox

actor Jugador

participant "Ventana Principal" as Principal
participant "Ventana Parámetros Individuos" as Opciones
participant "Ventana Parámetros Tablero" as Opciones2
participant "Ventana Parámetros Recurso" as Ajustes
participant "Tablero" as Tablero
participant "Bucle de Control" as Control

Jugador -> Principal: Abrir juego
Principal -> Principal: Mostrar opciones
Jugador -> Principal: Seleccionar 'Nueva Partida'
Principal -> Opciones: Mostrar ventana de opciones
Jugador -> Opciones: Ajustar parámetros
Opciones -> Opciones: Procesar cambios
Opciones -> Ajustes: Mostrar ventana de parámetros recursos
Jugador -> Ajustes: Ajustar parámetros
Ajustes -> Ajustes: Procesar ajustes
Jugador -> Opciones2: Ajustar parámetros
Opciones2 -> Opciones2: Procesar cambios
Jugador -> Opciones2: Crear Tablero
Opciones2 -> Tablero: Crear tablero
Tablero -> Control: Iniciar bucle de control
Control -> Control: Pasar Turnos
Control -> Tablero: Mostrar cambios
Jugador -> Tablero: Interactuar con botones
Tablero -> Control: Pausar juego
Control -> Tablero: Continuar bucle de control
Jugador -> Tablero: Interactuar con botones
Tablero -> Control: Terminar juego
Control -> "Pantalla Final": Finalizar juego
"Pantalla Final" -> "Pantalla Resultados": Mostrar información final
@enduml

